### ISSUE TITLE
Add :quelpa keyword

### ISSUE THREAD

**Issue by The-BigDaddy** [conao3/leaf-keywords.el#45]
Like how Quelpa provides [quelpa-use-package](https://framagit.org/steckerhalter/quelpa-use-package).

**Comment by conao3** [comment]
It's quite easy to add it, but think a bit more about how to order it.
I'm starting to think about not adding `quelpa` permanently from this package.

Do you have any comments?

**Comment by The-BigDaddy** [comment]
Would it only be a matter of adding it to `leaf-keywords-after-conditions`? The `quelpa-use-package` takes a symbol (the package name or just `t`) and 3 keywords; `:fetcher`, `:repo`, and `:upgrade`. `:fetcher` and `:repo` depend on each other (or at least I think they do).

> I'm starting to think about not adding `quelpa` permanently from this package.

What makes you say that? Does it seem unnecessary? 

There are times where there are forks that are not in MELPA and are more up-to-date. The one that comes to mind, for me is [vterm](https://github.com/jixiuf/emacs-libvterm).

**Comment by conao3** [comment]
Just add a routine to `leaf-keyword-normalize` that standardizes the arguments well, then add Sexp generator to `leaf-keyword-after-conditions`. An implementation like `:el-get` is quite simple.

I don't understand the story of vterm at all. Please explain a little more.

**Comment by The-BigDaddy** [comment]
> Just add a routine to `leaf-keyword-normalize` that standardizes the arguments well, then add Sexp generator to `leaf-keyword-after-conditions`. An implementation like `:el-get` is quite simple.

Got it. I'll give that a go later.

> I don't understand the story of vterm at all. Please explain a little more.

There's not really a story. The repo I linked is forked from the one that's available in MELPA, and is [more frequently updated](https://github.com/jixiuf/emacs-libvterm/commit/bf941088ddce6472a2bca10067007b6fbc0f5f84).

So it would make sense, for those cases, to provide a means to grab forks that might night be in MELPA.

If it seems reasonable, I can start working on implementing a `:quelpa` later today.

**Comment by conao3** [comment]
I can legally import the code you have modified to be based on my code without you having to send a PR to my repository. This is because the code in this repository is distributed in AGPL3. see [LICENSE](https://github.com/conao3/leaf-keywords.el/blob/master/LICENSE)

And I don't like the spread of `leaf` extension keywords. I think it is absurd that users download packages one by one for each keyword.

**Comment by conao3** [comment]
And see [MELPA top page](https://melpa.org/#/).

> Up-to-date packages built on our servers from upstream source
Installable in any Emacs with 'package.el' - no local version-control tools needed
Curated - no obsolete, renamed, forked or randomly hacked packages
Comprehensive - more packages than any other archive
Automatic updates - new commits result in new packages
Extensible - contribute recipes via github, and we'll build the packages

The line associated with you is
> Curated - no obsolete, renamed, forked or randomly hacked packages

You are not restricted from making changes to my code base at all, but it would be impossible to add it to MELPA. That is because it is against the philosophy of MELPA.

**Comment by The-BigDaddy** [comment]
That's fair. It's not troublesome to install Quelpa and use it by itself sans `leaf`. 

Frankly, the amount of keywords already seem sufficient.

At most, one could make some sort of...I don't know, `:git` keyword that will pull a package from some git repo and check for updates along with `package.el`.

I think my suggestion might not be necessary.

**Comment by conao3** [comment]
I take part in all the discussions that make the `leaf` better.
Anyway, thank you for your interest in my package.

If you have any other request, please suggest it on another occasion.
